// description  = descripcion
// buildingCode = codigo de edificio
// latitude = latitud
// longitude = longitud
// group = grupo
// initials = sigla

// Hay 76 objetos en el array

export const dataUAGRM = [
  // {
  //   description: "COMEDOR UNICERSITARIO",
  //   buildingCode: 292,
  //   latitude: -17.775615,
  //   longitude: -63.198539,
  //   group: "Oficinas Administrativas",
  //   initials: "COMEDOR UNICERSITARI",
  // },
  // {
  //   description: "ESTACIONAMIENTO GENERAL",
  //   buildingCode: 294,
  //   latitude: -17.776145,
  //   longitude: -63.197362,
  //   group: "Oficinas Administrativas",
  //   initials: "ESTACIO GENERAL",
  // },
  // {
  //   description: "CANCHA 1",
  //   buildingCode: 294,
  //   latitude: -17.776376,
  //   longitude: -63.197387,
  //   group: "Oficinas Administrativas",
  //   initials: "CANCHA 1",
  // },
  // {
  //   description: "CANCHA 2",
  //   buildingCode: 294,
  //   latitude: -17.776511,
  //   longitude: -63.19741,
  //   group: "Oficinas Administrativas",
  //   initials: "CANCHA 2",
  // },
  // {
  //   description:
  //     "DEPARTAMENTO DE EDUCACION A DISTANCIA Y TECNOLOGIA EDUCATIVA DEDTE",
  //   buildingCode: 126,
  //   latitude: -17.778044,
  //   longitude: -63.191087,
  //   group: "Oficinas Administrativas",
  //   initials: "DEDTE",
  // },
  // {
  //   description: "DEFENSOR UNIVERSITARIO",
  //   buildingCode: 126,
  //   latitude: -17.778208,
  //   longitude: -63.191071,
  //   group: "Oficinas Administrativas",
  //   initials: "DEFENSOR UNIVERSITAR",
  // },
  // {
  //   description: "INFORMACION CUP-PSA",
  //   buildingCode: 145,
  //   latitude: -17.778685,
  //   longitude: -63.190615,
  //   group: "Oficinas Administrativas",
  //   initials: "SECCION NF. CUP-PSA",
  // },
  // {
  //   description: "VICERRECTORADO",
  //   buildingCode: 90,
  //   latitude: -17.778333,
  //   longitude: -63.191472,
  //   group: "Oficinas Administrativas",
  //   initials: "VICERRECTORADO",
  // },
  // {
  //   description: "CLINICA ODONTOLOGICA",
  //   buildingCode: 91,
  //   latitude: -17.777989,
  //   longitude: -63.190801,
  //   group: "Oficinas Administrativas",
  //   initials: "CLINICA ODONTOLOGICA",
  // },
  // {
  //   description: "UNIDAD DE POSTGRADO DE CIENCIAS EXACTAS Y TECNOLOG?A",
  //   buildingCode: 93,
  //   latitude: -17.778037,
  //   longitude: -63.190458,
  //   group: "Oficinas Administrativas",
  //   initials: "PTGRDO FAC. TEC.",
  // },
  // {
  //   description: "ESTACIONAMIENTO DE LA FCET",
  //   buildingCode: 95,
  //   latitude: -17.778404,
  //   longitude: -63.191101,
  //   group: "Oficinas Administrativas",
  //   initials: "ESTACIO. FCET",
  // },
  // {
  //   description: "UNIDAD DE POSTGRADO DE LA FACULTAD DE HUMANIDADES",
  //   buildingCode: "",
  //   latitude: -17.77632,
  //   longitude: -63.19096,
  //   group: "Oficinas Administrativas",
  //   initials: "PTGRDO FAC. HUM",
  // },
  // {
  //   description: "DIRECCION UNIVERSITARIA DE INVESTIGACION DUI",
  //   buildingCode: 150,
  //   latitude: -17.776472,
  //   longitude: -63.190828,
  //   group: "Oficinas Administrativas",
  //   initials: "DUI",
  // },
  // {
  //   description: "DIRECCION DE INVESTIGACION DICIF",
  //   buildingCode: 150,
  //   latitude: -17.776491,
  //   longitude: -63.190886,
  //   group: "Oficinas Administrativas",
  //   initials: "DICIT",
  // },
  // {
  //   description: "DECANATO DE FACULTAD DE CIENCIA DE LA SALUD HUMANA",
  //   buildingCode: "",
  //   latitude: -17.776702,
  //   longitude: -63.190942,
  //   group: "Oficinas Administrativas",
  //   initials: "DECA. FACULTAD CSH",
  // },
  // {
  //   description: "UNIDAD DE POSTGRADO DE LA SALUD HUMANA",
  //   buildingCode: "",
  //   latitude: -17.776695,
  //   longitude: -63.190845,
  //   group: "Oficinas Administrativas",
  //   initials: "PTGRO FAC. SALUD",
  // },
  // {
  //   description: "DIRECCION DE CARRERA DE INGENIERIA INDUSTRIAL",
  //   buildingCode: "",
  //   latitude: -17.775283,
  //   longitude: -63.194561,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. INDUSTR",
  // },
  // {
  //   description: "VICEDECANATO FACULTAD DE CIENCIAS EXACTAS Y TECNOLOGIA",
  //   buildingCode: "",
  //   latitude: -17.775519,
  //   longitude: -63.195685,
  //   group: "Oficinas Administrativas",
  //   initials: "VICEDECANATO FCET",
  // },
  // {
  //   description:
  //     "DIRECCION DE LA CARRERA DE INGENIERIA EN CONTROL DE PROCESOS QUIMICA INDUSTRIAL",
  //   buildingCode: "",
  //   latitude: -17.775511,
  //   longitude: -63.195682,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR: ING CTRL PROCE",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA PETROLERA",
  //   buildingCode: "",
  //   latitude: -17.775515,
  //   longitude: -63.195688,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. PETROLERA",
  // },
  // {
  //   description:
  //     "DECANATO DE LA FACULTAD DE CIENCIAS EXACTA Y TECNOLOGIAS FGET",
  //   buildingCode: "",
  //   latitude: -17.775455,
  //   longitude: -63.195742,
  //   group: "Oficinas Administrativas",
  //   initials: "DECA. FACULTAD  FCET",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA QUIMICA",
  //   buildingCode: "",
  //   latitude: -17.775459,
  //   longitude: -63.195744,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. QUIMICA",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA EN ALIMENTOS",
  //   buildingCode: "",
  //   latitude: -17.775514,
  //   longitude: -63.195702,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. ALIMENTOS",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA AMBIENTAL",
  //   buildingCode: "",
  //   latitude: -17.775515,
  //   longitude: -63.195705,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. AMBIENTAL",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA CIVIL",
  //   buildingCode: "",
  //   latitude: -17.775519,
  //   longitude: -63.195708,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. CIVIL",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE INGENIERIA ELECTROMECANICA",
  //   buildingCode: "",
  //   latitude: -17.775528,
  //   longitude: -63.195659,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. ELECTROME",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA DE COMERCIO INTERNACIONAL",
  //   buildingCode: "",
  //   latitude: -17.77553,
  //   longitude: -63.195601,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. COMERCION INTE",
  // },
  // {
  //   description: "ESTACIONAMIENTO FCET",
  //   buildingCode: "",
  //   latitude: -17.775043,
  //   longitude: -63.1956,
  //   group: "Oficinas Administrativas",
  //   initials: "ESTACIONA. FCET",
  // },
  // {
  //   description: "DIRECCION DE LA CARRERA GESTION DEL TURISMO",
  //   buildingCode: 151,
  //   latitude: -17.777784,
  //   longitude: -63.191545,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. GESTION DE TUR",
  // },
  // {
  //   description: "JEFATURA MUSEO NOEL KENF MERCADO",
  //   buildingCode: 152,
  //   latitude: -17.777531,
  //   longitude: -63.191661,
  //   group: "Oficinas Administrativas",
  //   initials: "MUSEO NOEL KENF M.",
  // },
  // {
  //   description: "DIRECCION DE TECNOLOGIAS DE LA INF, Y COMUNICACI?",
  //   buildingCode: 9001,
  //   latitude: -17.777146,
  //   longitude: -63.190794,
  //   group: "Oficinas Administrativas",
  //   initials: "DTIC",
  // },
  // {
  //   description: "DEPARTAMENTOS",
  //   buildingCode: 9001,
  //   latitude: -17.777186,
  //   longitude: -63.190777,
  //   group: "Oficinas Administrativas",
  //   initials: "SECCION TITULOS",
  // },
  // {
  //   description: "VENTANILLAS AUXILIARES",
  //   buildingCode: 9001,
  //   latitude: -17.777284,
  //   longitude: -63.190729,
  //   group: "Oficinas Administrativas",
  //   initials: "VENTANILLAS AUXILIAR",
  // },
  // {
  //   description: "INFORMACION",
  //   buildingCode: 9002,
  //   latitude: -17.777426,
  //   longitude: -63.190579,
  //   group: "Oficinas Administrativas",
  //   initials: "INFORMACION",
  // },
  // {
  //   description: "DEPARTAMENTO DE TRAMITE REGISTRO Y TITULOS",
  //   buildingCode: 9002,
  //   latitude: -17.7775,
  //   longitude: -63.190551,
  //   group: "Oficinas Administrativas",
  //   initials: "DPTO. REG. Y TITULO",
  // },
  // {
  //   description: "CERTIFICADO NO DEUDOR",
  //   buildingCode: 9002,
  //   latitude: -17.777348,
  //   longitude: -63.190401,
  //   group: "Oficinas Administrativas",
  //   initials: "CERTIF. NO DEUDO",
  // },
  // {
  //   description: "FEDERACION UNIVERSITARIA DE AUXILIARES DE DOCENCIA",
  //   buildingCode: 9002,
  //   latitude: -17.777362,
  //   longitude: -63.190439,
  //   group: "Oficinas Administrativas",
  //   initials: "FUAD",
  // },
  // {
  //   description: "ADMINISTRACION PREDIOS DEL CAMPUS UNIVERSITARIOS",
  //   buildingCode: 9003,
  //   latitude: -17.777269,
  //   longitude: -63.190394,
  //   group: "Oficinas Administrativas",
  //   initials: "ADMI. CAMPUS",
  // },
  // {
  //   description: "DIRECCION DE CARRERA INGENIERIA INFORMATICA",
  //   buildingCode: 236,
  //   latitude: -17.776183,
  //   longitude: -63.195021,
  //   group: "Oficinas Administrativas",
  //   initials: "ING. INFORMATICA",
  // },
  // {
  //   description: "DIRECCION DE CARRERA INGENIERIA EN SISTEMAS",
  //   buildingCode: 236,
  //   latitude: -17.776183,
  //   longitude: -63.195021,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. DE SIST.",
  // },
  // {
  //   description:
  //     "DIRECCION DE CARRERA INGENIERIA EN REDES Y TELECOMUNICACIONES",
  //   buildingCode: 236,
  //   latitude: -17.776183,
  //   longitude: -63.195021,
  //   group: "Oficinas Administrativas",
  //   initials: "CARR. ING. EN REDES",
  // },
  // {
  //   description:
  //     "DECANATO DE LA FACULTAD DE CIENCIAS DE LA COMPUTACION Y TELECOMUNICACIONES FICCT",
  //   buildingCode: 236,
  //   latitude: -17.776183,
  //   longitude: -63.195021,
  //   group: "Oficinas Administrativas",
  //   initials: "DECANATO FICCT",
  // },
  // {
  //   description:
  //     "UNIDAD DE POSTGRADO E LA FACULTAD DE CIENCIAS DE LA COMPUTACION Y TELECOMUNICACIONES FICCT",
  //   buildingCode: 236,
  //   latitude: -17.776844,
  //   longitude: -63.195632,
  //   group: "Oficinas Administrativas",
  //   initials: "PTGRDO FICCT",
  // },
  // {
  //   description: "Modulo 117",
  //   buildingCode: 117,
  //   latitude: -17.777068,
  //   longitude: -63.191645,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 117",
  // },
  // {
  //   description: "Modulo 122",
  //   buildingCode: 122,
  //   latitude: -17.778244,
  //   longitude: -63.190365,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 122",
  // },

  // {
  //   description: "Modulo 123",
  //   buildingCode: 123,
  //   latitude: -17.778438,
  //   longitude: -63.190318,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 123",
  // },

  // {
  //   description: "Modulo 124",
  //   buildingCode: 124,
  //   latitude: -17.778474,
  //   longitude: -63.190523,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 124",
  // },
  // {
  //   description: "Modulo 125",
  //   buildingCode: 125,
  //   latitude: -17.778658,
  //   longitude: -63.190463,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 125",
  // },
  // {
  //   description: "Modulo 126",
  //   buildingCode: 126,
  //   latitude: -17.77808,
  //   longitude: -63.19108,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 126",location: "",
  // },
  // {
  //   description: "Modulo 127",
  //   buildingCode: 127,
  //   latitude: -17.778224,
  //   longitude: -63.190798,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 127",location: "",
  // },
  // {
  //   description: "Modulo 128",
  //   buildingCode: 128,
  //   latitude: -17.777548,
  //   longitude: -63.190964,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 128",location: "",
  // },
  // {
  //   description: "Modulo 145",
  //   buildingCode: 145,
  //   latitude: -17.778875,
  //   longitude: -63.190396,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 145",location: "",
  // },
  // {
  //   description: "Modulo 146",
  //   buildingCode: 146,
  //   latitude: -17.777198,
  //   longitude: -63.191485,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 146",location: "",
  // },
  // {
  //   description: "Modulo 150",
  //   buildingCode: 150,
  //   latitude: -17.776531,
  //   longitude: -63.190607,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 150",location: "",
  // },
  // {
  //   description: "Modulo 151",
  //   buildingCode: 151,
  //   latitude: -17.777867,
  //   longitude: -63.19161,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 151",location: "",
  // },
  // {
  //   description: "Modulo 153",
  //   buildingCode: 153,
  //   latitude: -17.777421,
  //   longitude: -63.191203,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 153",
  // },
  // {
  //   description: "Modulo 165",
  //   buildingCode: 165,
  //   latitude: -17.776869,
  //   longitude: -63.191178,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 165",
  // },
  // {
  //   description: "Modulo 175",
  //   buildingCode: 175,
  //   latitude: -17.775502,
  //   longitude: -63.191272,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 175",
  // },
  // {
  //   description: "Modulo 212",
  //   buildingCode: 212,
  //   latitude: -17.775594,
  //   longitude: -63.193736,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 212",
  // },
  // {
  //   description: "Modulo 213",
  //   buildingCode: 213,
  //   latitude: -17.776334,
  //   longitude: -63.193672,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 213",
  // },
  // {
  //   description: "Modulo 214",
  //   buildingCode: 214,
  //   latitude: -17.776667,
  //   longitude: -63.193803,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 214",
  // },
  // {
  //   description: "Modulo 224",
  //   buildingCode: 224,
  //   latitude: -17.775246,
  //   longitude: -63.194516,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 224",
  // },
  // {
  //   description: "Modulo 225",
  //   buildingCode: 225,
  //   latitude: -17.775587,
  //   longitude: -63.194741,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 225",
  // },
  // {
  //   description: "Modulo 228",
  //   buildingCode: 228,
  //   latitude: -17.776881,
  //   longitude: -63.194884,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 228",
  // },
  // {
  //   description: "Modulo 229",
  //   buildingCode: 229,
  //   latitude: -17.776992,
  //   longitude: -63.194475,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 229",
  // },
  // {
  //   description: "Modulo 233",
  //   buildingCode: 233,
  //   latitude: -17.774549,
  //   longitude: -63.195329,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 233",
  // },
  // {
  //   description: "Modulo 236",
  //   buildingCode: 236,
  //   latitude: -17.776487,
  //   longitude: -63.195077,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 236",
  // },
  // {
  //   description: "Modulo 244",
  //   buildingCode: 244,
  //   latitude: -17.77545,
  //   longitude: -63.195543,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 244",
  // },
  // {
  //   description: "Modulo 246",
  //   buildingCode: 246,
  //   latitude: -17.776925,
  //   longitude: -63.195924,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 246",
  // },
  // {
  //   description: "Modulo 247",
  //   buildingCode: 247,
  //   latitude: -17.777072,
  //   longitude: -63.195956,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 247",
  // },
  // {
  //   description: "Modulo 255",
  //   buildingCode: 255,
  //   latitude: -17.776116,
  //   longitude: -63.196554,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 255",
  // },
  // {
  //   description: "Modulo 256",
  //   buildingCode: 256,
  //   latitude: -17.776314,
  //   longitude: -63.196269,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 256",
  // },
  // {
  //   description: "Modulo 264",
  //   buildingCode: 264,
  //   latitude: -17.77633,
  //   longitude: -63.196951,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 264",
  // },
  // {
  //   description: "Modulo 265",
  //   buildingCode: 265,
  //   latitude: -17.776681,
  //   longitude: -63.196732,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 265",
  // },
  // {
  //   description: "Modulo 283",
  //   buildingCode: 283,
  //   latitude: -17.776046,
  //   longitude: -63.198198,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 283",
  // },
  // {
  //   description: "Modulo 284",
  //   buildingCode: 284,
  //   latitude: -17.77628,
  //   longitude: -63.19812,
  //   group: "Aulas y Laboratorios",
  //   initials: "Modulo 284",
  // },
  // TODO: DATOS VERSION 2 
  {
    description: "ADMINISTRACION PREDIOS DEL CAMPUS UNIVERSITARIOS",
    buildingCode: 9003,
    latitude: -17.777269,
    longitude: -63.190393999999998,
    group: "Oficinas Administrativas",
    initials: "ADMI",
    location: "Santa Cruz",
  },
  {
    description: "CANCHA 1",
    buildingCode: 294,
    latitude: -17.776375999999999,
    longitude: -63.197386999999999,
    group: "Oficinas Administrativas",
    initials: "CANCHA 1",
    location: "Santa Cruz",
  },
  {
    description: "CANCHA 2",
    buildingCode: 294,
    latitude: -17.776510999999999,
    longitude: -63.197409999999998,
    group: "Oficinas Administrativas",
    initials: "CANCHA 2",
    location: "Santa Cruz",
  },
  {
    description: "CLINICA ODONTOLOGICA",
    buildingCode: 91,
    latitude: -17.777989000000002,
    longitude: -63.190801,
    group: "Oficinas Administrativas",
    initials: "CLINICA ODONTOLOGICA",
    location: "Santa Cruz",
  },
  {
    description: "COMEDOR UNIVERSITARIO",
    buildingCode: 292,
    latitude: -17.775614999999998,
    longitude: -63.198538999999997,
    group: "Oficinas Administrativas",
    initials: "COMEDOR UNIVERSITARIO",
    location: "Santa Cruz",
  },
  {
    description: "DIRECCION DE TECNOLOGIAS DE LA INF, Y COMUNICACIÓN. DTIC",
    buildingCode: 9001,
    latitude: -17.777145999999998,
    longitude: -63.190793999999997,
    group: "Oficinas Administrativas",
    initials: "DTIC",
    location: "Santa Cruz",
  },
  {
    description: "ESTACIONAMIENTO DE LA FCET",
    buildingCode: 95,
    latitude: -17.778403999999998,
    longitude: -63.191101000000003,
    group: "Oficinas Administrativas",
    initials: "ESTACIO. FCET",
    location: "Santa Cruz",
  },
  {
    description: "ESTACIONAMIENTO DE LA FCET",
    buildingCode: "",
    latitude: -17.775043,
    longitude: -63.195599999999999,
    group: "Oficinas Administrativas",
    initials: "ESTACIONA. FCET",
    location: "Santa Cruz",
  },
  {
    description: "ESTACIONAMIENTO GENERAL",
    buildingCode: 294,
    latitude: -17.776145,
    longitude: -63.197361999999998,
    group: "Oficinas Administrativas",
    initials: "ESTACIO GENERAL",
    location: "Santa Cruz",
  },
  {
    description: "FEDERACION UNIVERSITARIA DE AUXILIARES DE DOCENCIA",
    buildingCode: 9002,
    latitude: -17.777362,
    longitude: -63.190438999999998,
    group: "Oficinas Administrativas",
    initials: "FUAD",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 117",
    buildingCode: 117,
    latitude: -17.777068,
    longitude: -63.191645000000001,
    group: "Aulas y Laboratorios",
    initials: "Modulo 117",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 122",
    buildingCode: 122,
    latitude: -17.778244000000001,
    longitude: -63.190365,
    group: "Aulas y Laboratorios",
    initials: "Modulo 122",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 123",
    buildingCode: 123,
    latitude: -17.778438000000001,
    longitude: -63.190317999999998,
    group: "Aulas y Laboratorios",
    initials: "Modulo 123",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 124",
    buildingCode: 124,
    latitude: -17.778473999999999,
    longitude: -63.190522999999999,
    group: "Aulas y Laboratorios",
    initials: "Modulo 124",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 125",
    buildingCode: 125,
    latitude: -17.778658,
    longitude: -63.190463000000001,
    group: "Aulas y Laboratorios",
    initials: "Modulo 125",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 126",
    buildingCode: 126,
    latitude: -17.778079999999999,
    longitude: -63.191079999999999,
    group: "Aulas y Laboratorios",
    initials: "Modulo 126",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 127",
    buildingCode: 127,
    latitude: -17.778224000000002,
    longitude: -63.190798000000001,
    group: "Aulas y Laboratorios",
    initials: "Modulo 127",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 128",
    buildingCode: 128,
    latitude: -17.777547999999999,
    longitude: -63.190964000000001,
    group: "Aulas y Laboratorios",
    initials: "Modulo 128",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 145",
    buildingCode: 145,
    latitude: -17.778874999999999,
    longitude: -63.190396,
    group: "Aulas y Laboratorios",
    initials: "Modulo 145",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 146",
    buildingCode: 146,
    latitude: -17.777197999999999,
    longitude: -63.191485,
    group: "Aulas y Laboratorios",
    initials: "Modulo 146",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 150",
    buildingCode: 150,
    latitude: -17.776530999999999,
    longitude: -63.190607,
    group: "Aulas y Laboratorios",
    initials: "Modulo 150",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 151",
    buildingCode: 151,
    latitude: -17.777867000000001,
    longitude: -63.191609999999997,
    group: "Aulas y Laboratorios",
    initials: "Modulo 151",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 153",
    buildingCode: 153,
    latitude: -17.777421,
    longitude: -63.191203,
    group: "Aulas y Laboratorios",
    initials: "Modulo 153",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 165",
    buildingCode: 165,
    latitude: -17.776869,
    longitude: -63.191178,
    group: "Aulas y Laboratorios",
    initials: "Modulo 165",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 175",
    buildingCode: 175,
    latitude: -17.775502,
    longitude: -63.191272,
    group: "Aulas y Laboratorios",
    initials: "Modulo 175",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 212",
    buildingCode: 212,
    latitude: -17.775594,
    longitude: -63.193736,
    group: "Aulas y Laboratorios",
    initials: "Modulo 212",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 213",
    buildingCode: 213,
    latitude: -17.776334,
    longitude: -63.193672,
    group: "Aulas y Laboratorios",
    initials: "Modulo 213",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 214",
    buildingCode: 214,
    latitude: -17.776667,
    longitude: -63.193803,
    group: "Aulas y Laboratorios",
    initials: "Modulo 214",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 224",
    buildingCode: 224,
    latitude: -17.775246,
    longitude: -63.194516,
    group: "Aulas y Laboratorios",
    initials: "Modulo 224",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 225",
    buildingCode: 225,
    latitude: -17.775587,
    longitude: -63.194741,
    group: "Aulas y Laboratorios",
    initials: "Modulo 225",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 228",
    buildingCode: 228,
    latitude: -17.776881,
    longitude: -63.194884,
    group: "Aulas y Laboratorios",
    initials: "Modulo 228",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 229",
    buildingCode: 229,
    latitude: -17.776992,
    longitude: -63.194475,
    group: "Aulas y Laboratorios",
    initials: "Modulo 229",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 233",
    buildingCode: 233,
    latitude: -17.774549,
    longitude: -63.195329,
    group: "Aulas y Laboratorios",
    initials: "Modulo 233",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 236",
    buildingCode: 236,
    latitude: -17.776487,
    longitude: -63.195077,
    group: "Aulas y Laboratorios",
    initials: "Modulo 236",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 244",
    buildingCode: 244,
    latitude: -17.77545,
    longitude: -63.195543,
    group: "Aulas y Laboratorios",
    initials: "Modulo 244",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 246",
    buildingCode: 246,
    latitude: -17.776925,
    longitude: -63.195924,
    group: "Aulas y Laboratorios",
    initials: "Modulo 246",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 247",
    buildingCode: 247,
    latitude: -17.777072,
    longitude: -63.195956,
    group: "Aulas y Laboratorios",
    initials: "Modulo 247",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 255",
    buildingCode: 255,
    latitude: -17.776116,
    longitude: -63.196554,
    group: "Aulas y Laboratorios",
    initials: "Modulo 255",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 256",
    buildingCode: 256,
    latitude: -17.776314,
    longitude: -63.196269,
    group: "Aulas y Laboratorios",
    initials: "Modulo 256",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 264",
    buildingCode: 264,
    latitude: -17.77633,
    longitude: -63.196951,
    group: "Aulas y Laboratorios",
    initials: "Modulo 264",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 265",
    buildingCode: 265,
    latitude: -17.776681,
    longitude: -63.196732,
    group: "Aulas y Laboratorios",
    initials: "Modulo 265",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 283",
    buildingCode: 283,
    latitude: -17.776046,
    longitude: -63.198198,
    group: "Aulas y Laboratorios",
    initials: "Modulo 283",
    location: "Santa Cruz",
  },
  {
    description: "Modulo 284",
    buildingCode: 284,
    latitude: -17.77628,
    longitude: -63.19812,
    group: "Aulas y Laboratorios",
    initials: "Modulo 284",
    location: "Santa Cruz",
  },
  {
    description: "VENTANILLAS AUXILIARES",
    buildingCode: 9001,
    latitude: -17.777284,
    longitude: -63.190729,
    group: "Oficinas Administrativas",
    initials: "VENTANILLAS AUXILIAR",
    location: "Santa Cruz",
  },
  {
    description: "VICERRECTORADO",
    buildingCode: 90,
    latitude: -17.778333,
    longitude: -63.191472,
    group: "Oficinas Administrativas",
    initials: "VICERRECTORADO",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura FINOR",
    buildingCode: "",
    latitude: -17.33861,
    longitude: -63.269031,
    group: "Oficinas Administrativas",
    initials: "Dec. FINOR",
    location: "Montero",
  },
  {
    description: "Carrera de Ciencias de la Educación",
    buildingCode: "",
    latitude: -17.338454,
    longitude: -63.268856,
    group: "Oficinas Administrativas",
    initials: "Carr Cs de la Educacion",
    location: "Montero",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -17.338461,
    longitude: -63.268878,
    group: "Oficinas Administrativas",
    initials: "Carr Cont. Pública",
    location: "Montero",
  },
  {
    description: "Carrera de Derecho",
    buildingCode: "",
    latitude: -17.338737,
    longitude: -63.269214,
    group: "Oficinas Administrativas",
    initials: "Carr Derecho",
    location: "Montero",
  },
  {
    description: "Carrera de Enfermería",
    buildingCode: "",
    latitude: -17.33825,
    longitude: -63.269033,
    group: "Oficinas Administrativas",
    initials: "Carr Enfermería",
    location: "Montero",
  },
  {
    description: "Carrera de Ingeniería Comercial",
    buildingCode: "",
    latitude: -17.352313,
    longitude: -63.263406,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Comercial",
    location: "Montero",
  },
  {
    description: "Carrera de Ingeniería Industrial",
    buildingCode: "",
    latitude: -17.339023,
    longitude: -63.26884,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Industrial",
    location: "Montero",
  },
  {
    description: "Carrera de Ingeniería Petrolera",
    buildingCode: "",
    latitude: -17.338388,
    longitude: -63.267917,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Petrolera",
    location: "Montero",
  },
  {
    description: "Carrera de Ingeniería en Sistemas",
    buildingCode: "",
    latitude: -17.338608,
    longitude: -63.268046,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Sistema",
    location: "Montero",
  },
  {
    description: "Carrera de Medicina",
    buildingCode: "",
    latitude: -17.339115,
    longitude: -63.269001,
    group: "Oficinas Administrativas",
    initials: "Carr Medicina",
    location: "Montero",
  },
  {
    description: "Carrera de Medicina Veterinaria y Zootecnia",
    buildingCode: "",
    latitude: -17.338941,
    longitude: -63.268679,
    group: "Oficinas Administrativas",
    initials: "Carr Med. Veterinaria",
    location: "Montero",
  },
  {
    description: "Decanatura Facultad Integral de los Valles Cruceños",
    buildingCode: "",
    latitude: -18.486226,
    longitude: -64.100892,
    group: "Oficinas Administrativas",
    initials: "Dec. FIVC",
    location: "Vallegrande",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -18.48632,
    longitude: -64.100708,
    group: "Oficinas Administrativas",
    initials: "Carr Cont. Pública",
    location: "Vallegrande",
  },
  {
    description: "Carrera de Ingeniería Agropecuaria",
    buildingCode: "",
    latitude: -18.486524,
    longitude: -64.101091,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Agro Agropecuaria",
    location: "Vallegrande",
  },
  {
    description: "Carrera de Ingeniería en Sistemas",
    buildingCode: "",
    latitude: -18.48643,
    longitude: -64.100775,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Sistema",
    location: "Vallegrande",
  },
  {
    description: "Decanatura Facultad Politécnica",
    buildingCode: "",
    latitude: -17.775377,
    longitude: -63.194199,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. Politécnica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Construcciones Civiles",
    buildingCode: "",
    latitude: -17.775442,
    longitude: -63.19377,
    group: "Oficinas Administrativas",
    initials: "Carr Construc. Civiles",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Electricidad Industrial",
    buildingCode: "",
    latitude: -17.775148,
    longitude: -63.193778,
    group: "Oficinas Administrativas",
    initials: "Carr Elect. Industrial",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Electrónica",
    buildingCode: "",
    latitude: -17.775702,
    longitude: -63.193775,
    group: "Oficinas Administrativas",
    initials: "Carr Electrónica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería en Agrimensura",
    buildingCode: "",
    latitude: -17.775624,
    longitude: -63.193756,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Agrimensura",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería en Materiales",
    buildingCode: "",
    latitude: -17.775225,
    longitude: -63.194125,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Materiales",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería en Metalurgia",
    buildingCode: "",
    latitude: -17.775225,
    longitude: -63.194125,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Metalurgica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Licenciatura en Ofimática",
    buildingCode: "",
    latitude: -17.775465,
    longitude: -63.193801,
    group: "Oficinas Administrativas",
    initials: "Carr Lic. En Ofimatica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Mecánica General",
    buildingCode: "",
    latitude: -17.775509,
    longitude: -63.194117,
    group: "Oficinas Administrativas",
    initials: "Carr Mecánica General",
    location: "Santa Cruz",
  },
  {
    description: "Unidades Académica El Torno",
    buildingCode: "",
    latitude: -17.981956,
    longitude: -63.373469,
    group: "Oficinas Administrativas",
    initials: "Unid. Académica El Torno",
    location: "El Torno",
  },
  {
    description: "Unidades Académica Puerto Suarez",
    buildingCode: "",
    latitude: -18.99419,
    longitude: -57.781132,
    group: "Oficinas Administrativas",
    initials: "Unid. Académica Pto. Suarez",
    location: "Puerto Suarez",
  },
  {
    description: "Decanatura Facultad de Ciencias Veterinarias",
    buildingCode: "",
    latitude: -17.776849,
    longitude: -63.194832,
    group: "Oficinas Administrativas",
    initials: "Decanatura Fac. Cs. Vete.",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Medicina Veterinaria y Zootecnia",
    buildingCode: "",
    latitude: -17.776849,
    longitude: -63.194832,
    group: "Oficinas Administrativas",
    initials: "Carr Medicina Veteria",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Humanidades",
    buildingCode: "",
    latitude: -17.774657,
    longitude: -63.196569,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. de Humanidades",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Actividad Física",
    buildingCode: "",
    latitude: -17.774743,
    longitude: -63.196738,
    group: "Oficinas Administrativas",
    initials: "Carr Actividad Físic",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ciencias de la Comunicación",
    buildingCode: "",
    latitude: -17.774733,
    longitude: -63.196552,
    group: "Oficinas Administrativas",
    initials: "Carr. Cs. de la Comunicación",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ciencias de la Educación",
    buildingCode: "",
    latitude: -17.774749,
    longitude: -63.196881,
    group: "Oficinas Administrativas",
    initials: "Carr Cs. de la Educacion",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Gestión del Turismo",
    buildingCode: "",
    latitude: -17.774485,
    longitude: -63.196777,
    group: "Oficinas Administrativas",
    initials: "Carr Gest. del Turismo",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Lenguas Modernas y Filología Hispánica",
    buildingCode: "",
    latitude: -17.782313,
    longitude: -63.179364,
    group: "Oficinas Administrativas",
    initials: "Carr Lenguas Moderna",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Psicología",
    buildingCode: "",
    latitude: -17.774738,
    longitude: -63.196543,
    group: "Oficinas Administrativas",
    initials: "Carr Psicología",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Sociología",
    buildingCode: "",
    latitude: -17.775046,
    longitude: -63.196938,
    group: "Oficinas Administrativas",
    initials: "Carr Sociología",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Ciencias Agrícolas",
    buildingCode: "",
    latitude: -17.699148,
    longitude: -63.147904,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. de Cs. Agricolas",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Biología",
    buildingCode: "",
    latitude: -17.698152,
    longitude: -63.147582,
    group: "Oficinas Administrativas",
    initials: "Carr Biología",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ciencias Ambientales",
    buildingCode: "",
    latitude: -17.698065,
    longitude: -63.147545,
    group: "Oficinas Administrativas",
    initials: "Carr Cs. Ambiental",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Agronómica",
    buildingCode: "",
    latitude: -17.69821,
    longitude: -63.14759,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Agronomica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera Ingeniería Agrícola (Montero)",
    buildingCode: "",
    latitude: -17.319111,
    longitude: -63.262142,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Agrícola",
    location: "Montero",
  },
  {
    description: "Carrera Ingeniería Forestal",
    buildingCode: "",
    latitude: -17.699676,
    longitude: -63.148063,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Foresta",
    location: "Santa Cruz",
  },
  {
    description:
      "Decanatura Facultad de Ciencias Contables, Auditoría, Sistemas de Control de Gestión y Finanzas",
    buildingCode: "",
    latitude: -17.776395,
    longitude: -63.194033,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. Cs. Contaduria",
    location: "Santa Cruz",
  },
  {
    description: "Carrea de Contaduría Pública",
    buildingCode: "",
    latitude: -17.776306,
    longitude: -63.194177,
    group: "Oficinas Administrativas",
    initials: "Carr Contad. Pública",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Información y Control de Gestión",
    buildingCode: "",
    latitude: -17.776704,
    longitude: -63.193857,
    group: "Oficinas Administrativas",
    initials: "Carr Infor. y Control de Gest.",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Ciencias de la Salud Humana",
    buildingCode: "",
    latitude: -17.774857,
    longitude: -63.197753,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. de Cs. Salu Hum.",
    location: "Santa Cruz",
  },
  {
    description: "Carrera Enfermería",
    buildingCode: "",
    latitude: -17.774909,
    longitude: -63.197662,
    group: "Oficinas Administrativas",
    initials: "Carr Enfermeria",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Medicina",
    buildingCode: "",
    latitude: -17.77525,
    longitude: -63.198152,
    group: "Oficinas Administrativas",
    initials: "Carr Medicina",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Odontología",
    buildingCode: "",
    latitude: -17.774964,
    longitude: -63.198322,
    group: "Oficinas Administrativas",
    initials: "Carr Odontología",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Ciencias del Hábitat, Diseño y Arte",
    buildingCode: "",
    latitude: -17.770112,
    longitude: -63.191995,
    group: "Oficinas Administrativas",
    initials: "Deca Fac. de Cs. Habitad",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Arquitectura",
    buildingCode: "",
    latitude: -17.770101,
    longitude: -63.192009,
    group: "Oficinas Administrativas",
    initials: "Carr Arquitectura",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Arte",
    buildingCode: "",
    latitude: -17.77992,
    longitude: -63.183385,
    group: "Oficinas Administrativas",
    initials: "Carr Arte",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Diseño Integral",
    buildingCode: "",
    latitude: -17.769779,
    longitude: -63.192049,
    group: "Oficinas Administrativas",
    initials: "Carr Diseño Integral",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Planificación Territorial",
    buildingCode: "",
    latitude: -17.769777,
    longitude: -63.191777,
    group: "Oficinas Administrativas",
    initials: "Carr Plani. Territorial",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad Integral del Chaco (FICH)",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Decanatura FICH",
    location: "Camiri",
  },
  {
    description: "Carrera de Administración de Empresas",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Administración",
    location: "Camiri",
  },
  {
    description: "Carrera de Ciencias de la Educación",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Cs. de la Educacion",
    location: "Camiri",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Cont. Pública",
    location: "Camiri",
  },
  {
    description: "Carrera de Derecho",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Derecho",
    location: "Camiri",
  },
  {
    description: "Carrera de Enfermería",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Enfermería",
    location: "Camiri",
  },
  {
    description: "Carrera de Ingeniería Industrial",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Industrial",
    location: "Camiri",
  },
  {
    description: "Carrera de Ingeniería Informática",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Informatica",
    location: "Camiri",
  },
  {
    description: "Carrera de Ingeniería del Petróleo y Gas Natural",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. del Petroleo y Gas",
    location: "Camiri",
  },
  {
    description: "Carrera de Ingeniería en Agropecuaria",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Agropecuaria",
    location: "Camiri",
  },
  {
    description: "Carrera de Ingeniería en Sistemas",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. En Sistema",
    location: "Camiri",
  },
  {
    description: "Carrera de Monitoreo Socioambiental",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Moni. Socio Amb.",
    location: "Camiri",
  },
  {
    description: "Carrera de Odontología",
    buildingCode: "",
    latitude: -20.033085,
    longitude: -63.527962,
    group: "Oficinas Administrativas",
    initials: "Carr Odontología",
    location: "Camiri",
  },
  {
    description: "Decanatura Facultad Integral del Noreste (FINE)",
    buildingCode: "",
    latitude: -16.910514,
    longitude: -62.621272,
    group: "Oficinas Administrativas",
    initials: "Deca Facultad FINE",
    location: "San Julian",
  },
  {
    description: "Carrera de Ciencias de la Educación",
    buildingCode: "",
    latitude: -16.910514,
    longitude: -62.621272,
    group: "Oficinas Administrativas",
    initials: "Carr Cs. de la Educacion",
    location: "San Julian",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -16.910514,
    longitude: -62.621272,
    group: "Oficinas Administrativas",
    initials: "Carr Cont. Pública",
    location: "San Julian",
  },
  {
    description: "Carrera de Enfermería",
    buildingCode: "",
    latitude: -16.910514,
    longitude: -62.621272,
    group: "Oficinas Administrativas",
    initials: "Carr Enfermería",
    location: "San Julian",
  },
  {
    description: "Carrera de Ing. Agropecuaria",
    buildingCode: "",
    latitude: -16.910514,
    longitude: -62.621272,
    group: "Oficinas Administrativas",
    initials: "Carr Ingeniería Agro",
    location: "San Julian",
  },
  {
    description:
      "Decanatura Facultad de Ingeniería en Ciencias de la Computación y Telecomunicaciones (FICCT)",
    buildingCode: "",
    latitude: -17.77613,
    longitude: -63.19499,
    group: "Oficinas Administrativas",
    initials: "Decanatura FICCT",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Informática",
    buildingCode: "",
    latitude: -17.77613,
    longitude: -63.19496,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Informatica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería en Redes y Telecomunicaciones",
    buildingCode: "",
    latitude: -17.77613,
    longitude: -63.19509,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Redes y Telf.",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería en Sistemas",
    buildingCode: "",
    latitude: -17.77613,
    longitude: -63.1951,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Sistema",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad Integral Chiquitana (FAICHI)",
    buildingCode: "",
    latitude: -16.384384,
    longitude: -60.967465,
    group: "Oficinas Administrativas",
    initials: "Deca FAICHI",
    location: "San Ignacio",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -16.38435,
    longitude: -60.96771,
    group: "Oficinas Administrativas",
    initials: "Carr Cont Pública",
    location: "San Ignacio",
  },
  {
    description: "Carrera de Ing. Agropecuaria",
    buildingCode: "",
    latitude: -16.38452,
    longitude: -60.96777,
    group: "Oficinas Administrativas",
    initials: "Carr Ingeniería Agro",
    location: "San Ignacio",
  },
  {
    description: "Carrera de Zootecnia",
    buildingCode: "",
    latitude: -16.38476,
    longitude: -60.96768,
    group: "Oficinas Administrativas",
    initials: "Carr Zootecnia",
    location: "San Ignacio",
  },
  {
    description: "Escalafón Docente",
    buildingCode: "",
    latitude: -17.777717,
    longitude: -63.191628,
    group: "Oficinas Administrativas",
    initials: "Escalafón Docente",
    location: "Santa Cruz",
  },
  {
    description: "Evaluación y Acreditación",
    buildingCode: "",
    latitude: -17.774557,
    longitude: -63.192523,
    group: "Oficinas Administrativas",
    initials: "Eval y Acreditación",
    location: "Santa Cruz",
  },
  {
    description: "Trámites y Registros",
    buildingCode: "",
    latitude: -17.777463,
    longitude: -63.190315,
    group: "Oficinas Administrativas",
    initials: "Trámites y Registros",
    location: "Santa Cruz",
  },
  {
    description: "Títulos",
    buildingCode: "",
    latitude: -17.7774,
    longitude: -63.190319,
    group: "Oficinas Administrativas",
    initials: "Títulos",
    location: "Santa Cruz",
  },
  {
    description:
      "Dirección de Investigación Científica e Innovación Tecnológica (DICiT)",
    buildingCode: "",
    latitude: -17.77618,
    longitude: -63.190899,
    group: "Oficinas Administrativas",
    initials: "Dire de Inv. (DICIT)",
    location: "Santa Cruz",
  },
  {
    description: "Escuela de Postgrado",
    buildingCode: "",
    latitude: -17.792669,
    longitude: -63.181845,
    group: "Oficinas Administrativas",
    initials: "Escuela de Postgrado",
    location: "Santa Cruz",
  },
  {
    description: "Orientación Vocacional",
    buildingCode: "",
    latitude: -17.778778,
    longitude: -63.192805,
    group: "Oficinas Administrativas",
    initials: "Orientación Vocacional",
    location: "Santa Cruz",
  },
  {
    description: "Corte Electoral Universitaria",
    buildingCode: "",
    latitude: -17.777776,
    longitude: -63.192049,
    group: "Oficinas Administrativas",
    initials: "Corte Electoral Universitaria",
    location: "Santa Cruz",
  },
  {
    description: "Defensoría Universitaria",
    buildingCode: "",
    latitude: -17.778565,
    longitude: -63.192848,
    group: "Oficinas Administrativas",
    initials: "Defensoría Universitaria",
    location: "Santa Cruz",
  },
  {
    description: "Tribunal de Justicia Universitaria",
    buildingCode: "",
    latitude: -17.777524,
    longitude: -63.192475,
    group: "Oficinas Administrativas",
    initials: "Tribunal de  Justicia Unive",
    location: "Santa Cruz",
  },
  {
    description: "Instituto de Capacitación Popular",
    buildingCode: "",
    latitude: -17.777668,
    longitude: -63.165449,
    group: "Oficinas Administrativas",
    initials: "ICAP",
    location: "Santa Cruz",
  },
  {
    description:
      "Instituto de Investigación de la Facultad de Humanidades (INIFH)",
    buildingCode: "",
    latitude: -17.774209,
    longitude: -63.196905,
    group: "Oficinas Administrativas",
    initials: "INIFH",
    location: "Santa Cruz",
  },
  {
    description: "Instituto de Investigaciones Agrícolas El Vallecito",
    buildingCode: "",
    latitude: -17.708482,
    longitude: -63.147389,
    group: "Oficinas Administrativas",
    initials: "Inst Inv. Vallecito",
    location: "Santa Cruz",
  },
  {
    description:
      "Instituto de Investigaciones Económicas y Sociales José Ortíz Mercado",
    buildingCode: "",
    latitude: -17.774241,
    longitude: -63.193981,
    group: "Oficinas Administrativas",
    initials: "Inst Inv. Eco. Soc.",
    location: "Santa Cruz",
  },
  {
    description: "Instituto de Investigaciones Forestales",
    buildingCode: "",
    latitude: -17.819368,
    longitude: -63.18146,
    group: "Oficinas Administrativas",
    initials: "Inst Inv. Forestal",
    location: "Santa Cruz",
  },
  {
    description: "Museo de Historia",
    buildingCode: "",
    latitude: -17.782958,
    longitude: -63.183188,
    group: "Oficinas Administrativas",
    initials: "Museo Historia",
    location: "Santa Cruz",
  },
  {
    description: "Museo de Historia Natural Noel Kempff Mercado",
    buildingCode: "",
    latitude: -17.792665,
    longitude: -63.18189,
    group: "Oficinas Administrativas",
    initials: "Museo Noel Kempff",
    location: "Santa Cruz",
  },
  {
    description: "Federación Universitaria de Profesores (FUP)",
    buildingCode: "",
    latitude: -17.774332,
    longitude: -63.19259,
    group: "Oficinas Administrativas",
    initials: "FUP",
    location: "Santa Cruz",
  },
  {
    description: "Federacion Universitaria Local (FUL)",
    buildingCode: "",
    latitude: -17.778436,
    longitude: -63.192302,
    group: "Oficinas Administrativas",
    initials: "FUL",
    location: "Santa Cruz",
  },
  {
    description: "Sindicato de Trabajadores Universitario (STU)",
    buildingCode: "",
    latitude: -17.779757,
    longitude: -63.190906,
    group: "Oficinas Administrativas",
    initials: "STU",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad Integral de Ichilo (FINI)",
    buildingCode: "",
    latitude: -17.396969,
    longitude: -63.877942,
    group: "Oficinas Administrativas",
    initials: "Deca FINI",
    location: "Yapacani",
  },
  {
    description: "Carrera de Administración de Empresas",
    buildingCode: "",
    latitude: -17.397058,
    longitude: -63.878022,
    group: "Oficinas Administrativas",
    initials: "Carr Administración",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ciencias de la Educación",
    buildingCode: "",
    latitude: -17.397019,
    longitude: -63.878004,
    group: "Oficinas Administrativas",
    initials: "Carr Cs de la Educacion",
    location: "Yapacani",
  },
  {
    description: "Carrera de Contaduría Pública",
    buildingCode: "",
    latitude: -17.396911,
    longitude: -63.87794,
    group: "Oficinas Administrativas",
    initials: "Carr Cont. Pública",
    location: "Yapacani",
  },
  {
    description: "Carrera de Derecho",
    buildingCode: "",
    latitude: -17.396943,
    longitude: -63.877957,
    group: "Oficinas Administrativas",
    initials: "Carr Derecho",
    location: "Yapacani",
  },
  {
    description: "Carrera de Enfermería",
    buildingCode: "",
    latitude: -17.396996,
    longitude: -63.877983,
    group: "Oficinas Administrativas",
    initials: "Carr Enfermería",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ingeniería Agropecuaria",
    buildingCode: "",
    latitude: -17.396933,
    longitude: -63.877921,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Agropecuaria",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ingeniería Comercial",
    buildingCode: "",
    latitude: -17.39706,
    longitude: -63.878011,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Comercial",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ingeniería Financiera",
    buildingCode: "",
    latitude: -17.39701,
    longitude: -63.87796,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Financiera",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ingeniería Petrolera",
    buildingCode: "",
    latitude: -17.39692,
    longitude: -63.8779,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Petrolera",
    location: "Yapacani",
  },
  {
    description: "Carrera de Ingeniería en Sistemas",
    buildingCode: "",
    latitude: -17.396945,
    longitude: -63.877933,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. en Sistema",
    location: "Yapacani",
  },
  {
    description: "Carrera de Medicina Veterinaria y Zootécnica",
    buildingCode: "",
    latitude: -17.396946,
    longitude: -63.877913,
    group: "Oficinas Administrativas",
    initials: "Carr Med. Veterinaria",
    location: "Yapacani",
  },
  {
    description: "Decanatura Facultad de Ciencias Económicas y Empresariales",
    buildingCode: "",
    latitude: -17.776131,
    longitude: -63.196476,
    group: "Oficinas Administrativas",
    initials: "Deca Fac de Cs. Eco",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Administración de Empresas",
    buildingCode: "",
    latitude: -17.776168,
    longitude: -63.196507,
    group: "Oficinas Administrativas",
    initials: "Carr Administración",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Comercio Internacional",
    buildingCode: "",
    latitude: -17.77553,
    longitude: -63.195601,
    group: "Oficinas Administrativas",
    initials: "Carr Comercio Intern",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Economía",
    buildingCode: "",
    latitude: -17.776116,
    longitude: -63.196581,
    group: "Oficinas Administrativas",
    initials: "Carr Economía",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Comercial",
    buildingCode: "",
    latitude: -17.776414,
    longitude: -63.197038,
    group: "Oficinas Administrativas",
    initials: "Carr Ingeniería Come",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Financiera",
    buildingCode: "",
    latitude: -17.776709,
    longitude: -63.196728,
    group: "Oficinas Administrativas",
    initials: "Carr Ingeniería Fina",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Ciencias Exactas y Tecnología",
    buildingCode: "",
    latitude: -17.775455,
    longitude: -63.195742,
    group: "Oficinas Administrativas",
    initials: "Deca FCET",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Ambiental",
    buildingCode: "",
    latitude: -17.775515,
    longitude: -63.195705,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Ambiental",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Civil",
    buildingCode: "",
    latitude: -17.775519,
    longitude: -63.195708,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Civil",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Electromecánica",
    buildingCode: "",
    latitude: -17.775528,
    longitude: -63.195659,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Electromecanica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Industrial",
    buildingCode: "",
    latitude: -17.775283,
    longitude: -63.194561,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Industrial",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Petrolera",
    buildingCode: "",
    latitude: -17.775515,
    longitude: -63.195688,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Petrolera",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería Química",
    buildingCode: "",
    latitude: -17.775459,
    longitude: -63.195744,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. Química",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería de Alimentos",
    buildingCode: "",
    latitude: -17.775514,
    longitude: -63.195702,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. de Alimentos",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ingeniería de Control de Procesos",
    buildingCode: "",
    latitude: -17.775511,
    longitude: -63.195682,
    group: "Oficinas Administrativas",
    initials: "Carr Ing. de Control Proc.",
    location: "Santa Cruz",
  },
  {
    description: "Decanatura Facultad de Ciencias Farmacéuticas y Bioquímicas",
    buildingCode: "",
    latitude: -17.774565,
    longitude: -63.197728,
    group: "Oficinas Administrativas",
    initials: "Decanatura FBF",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Bioquímica",
    buildingCode: "",
    latitude: -17.774591,
    longitude: -63.197938,
    group: "Oficinas Administrativas",
    initials: "Carr Bioquímica",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Farmacia",
    buildingCode: "",
    latitude: -17.77458,
    longitude: -63.197912,
    group: "Oficinas Administrativas",
    initials: "Carr Farmacia",
    location: "Santa Cruz",
  },
  {
    description:
      "Decanatura Facultad de Ciencias Jurídicas, Políticas, Sociales y Relaciones Internacionales",
    buildingCode: "",
    latitude: -17.775991,
    longitude: -63.198423,
    group: "Oficinas Administrativas",
    initials: "Decanatura Cs, Juridicas",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Ciencias Políticas y Administración Pública",
    buildingCode: "",
    latitude: -17.775834,
    longitude: -63.198232,
    group: "Oficinas Administrativas",
    initials: "Carr Cs. Política",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Derecho",
    buildingCode: "",
    latitude: -17.776012,
    longitude: -63.198332,
    group: "Oficinas Administrativas",
    initials: "Carr Derecho",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Relaciones Internacionales",
    buildingCode: "",
    latitude: -17.77603,
    longitude: -63.198106,
    group: "Oficinas Administrativas",
    initials: "Carr Relaciones Inte",
    location: "Santa Cruz",
  },
  {
    description: "Carrera de Trabajo Social",
    buildingCode: "",
    latitude: -17.775933,
    longitude: -63.19846,
    group: "Oficinas Administrativas",
    initials: "Carr Trabajo Social",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Auditoria Financiera o Contaduría Pública",
    buildingCode: "",
    latitude: -17.7795,
    longitude: -63.1912,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cont. Publica",
    location: "Santa Cruz",
  },
  {
    description: "Unidad de Postgrado de la Facultad de Ciencias Agrícolas",
    buildingCode: "",
    latitude: -17.7736,
    longitude: -63.1667,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Agricilas",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias de la Salud Humana",
    buildingCode: "",
    latitude: -17.7826,
    longitude: -63.1791,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Salud",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias del Hábitat, Diseño y Arte",
    buildingCode: "",
    latitude: -17.7701,
    longitude: -63.1921,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Habitad",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias Económicas y Empresariales",
    buildingCode: "",
    latitude: -17.7905,
    longitude: -63.1791,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Economicas",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias Exactas y Tecnología",
    buildingCode: "",
    latitude: -17.778,
    longitude: -63.1905,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Exactas y Tec.",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias Farmacéuticas y Bioquímicas",
    buildingCode: "",
    latitude: -17.7746,
    longitude: -63.1977,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Farmacia y Bio.",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias Jurídicas, Políticas, Sociales y RR.II.",
    buildingCode: "",
    latitude: -17.7792,
    longitude: -63.1926,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Cs. Juricas",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ciencias Veterinarias y Zootecnia",
    buildingCode: "",
    latitude: -17.7771,
    longitude: -63.1958,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Veternaria",
    location: "Santa Cruz",
  },
  {
    description: "Unidad de Postgrado de la Facultad de Humanidades",
    buildingCode: "",
    latitude: -17.7763,
    longitude: -63.1909,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Humanidades",
    location: "Santa Cruz",
  },
  {
    description:
      "Unidad de Postgrado de la Facultad de Ingeniería en Ciencias de la Computación y Telecomunicacione",
    buildingCode: "",
    latitude: -17.7741,
    longitude: -63.1953,
    group: "Oficinas Administrativas",
    initials: "Postgrado Cs. Computacion",
    location: "Santa Cruz",
  },
  {
    description: "Unidad de Postgrado de la Facultad Integral de Ichilo",
    buildingCode: "",
    latitude: -17.3967,
    longitude: -63.8787,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Ichilo",
    location: "Yapacani",
  },
  {
    description: "Unidad de Postgrado de la Facultad Integral del Chaco",
    buildingCode: "",
    latitude: -20.0334,
    longitude: -63.5279,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Chaco",
    location: "Camiri",
  },
  {
    description: "Unidad de Postgrado de la Facultad Integral del Noreste",
    buildingCode: "",
    latitude: -16.9105,
    longitude: -62.6208,
    group: "Oficinas Administrativas",
    initials: "Postgrado Fac. Noroeste",
    location: "San Julian",
  },
];
